---
# tasks file for roles/lb

- name: DPKG Ubuntu Package
  command: "dpkg --configure -a"
  tags: dpkg

- name: Updating apt packages
  apt:  name=* state=latest update_cache=yes force_apt_get=yes
  tags: apt-update

- name: Installing apache
  apt: 
    name:
      - apache2 
    state: present

- name: Enable proxy related modules
  apache2_module: name={{ item }} state=present
  with_items:
  - proxy
  - proxy_http
  - proxy_balancer
  - lbmethod_byrequests

- name: Create template
  template:  
    src: ./lbconf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    mode: 0644
  notify: restart apache

- name: HTML File Check
  stat: path=/var/www/html
  ignore_errors: yes
  register: index

- name: Move index.html to index.bkp
  command: mv /var/www/html/index.html /var/www/html/index.bkp
  when: index.stat.exists
  ignore_errors: yes
  notify: restart apache

- name: Ensure apache starts
  service: 
    name: apache2 
    state: started 
    enabled: yes
  tags: ensure-service-starts